brew "ansible"
brew "aspell"
brew "clisp"
brew "coreutils"
brew "ctags"
brew "ctop"
brew "dos2unix"
brew "emacs"
brew "enchant"
brew "exiftool"
brew "fd"
brew "ffmpeg"
brew "fish"
brew "gcc"
brew "git"
brew "gnupg"
brew "gradle"
brew "hub"
brew "jq"
brew "mas"
brew "maven"
brew "mitmproxy"
brew "mplayer"
brew "node@8"
brew "p7zip"
brew "pwgen"
brew "python"
brew "python@2"
brew "qpdf"
brew "ruby"
brew "ruby-build"
brew "scala"
brew "sergiobenitez/osxct/aarch64-none-elf"
brew "socat"
brew "terminal-notifier"
brew "the_silver_searcher"
brew "tmux"
brew "trash"
brew "watch"
brew "wget"
cask "alfred"
cask "dash"
cask "docker"
cask "spectacle"
cask "sublime-text"
mas "Bear", id: 1091189122
mas "Day One", id: 1055511498
mas "Fantastical 2", id: 975937182
mas "Pixelmator", id: 407963104
mas "Radium", id: 597611879
mas "Things3", id: 904280696
mas "Xcode", id: 497799835
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "sergiobenitez/osxct"
