# Packages from cfg Brewfile
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "aspell" # for emacs spell check
brew "coreutils"
brew "ctags" # auto-generated with git hooks
brew "dos2unix"
brew "emacs"
brew "enchant" # get spelling suggestions with `enchant-2 -a`
brew "exiftool"
brew "ffmpeg"
brew "fish"
brew "gcc"
brew "git"
brew "gnupg"
brew "jq"
brew "nvm"
brew "p7zip"
brew "pipenv"
brew "pwgen"
brew "python"
brew "terminal-notifier"
brew "the_silver_searcher"
brew "tmux"
brew "trash"
brew "watch"
brew "wget"
cask "alfred"
cask "bartender"
cask "hex-fiend"
cask "monodraw"
cask "spectacle"
cask "sublime-text"
cask "zulu15"
